version: '3.4'

services:
  georgianwebsite:
    image: georgianwebsite
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
